### ISSUE TITLE
FLutter编译桌面端app | zhe's home

### ISSUE THREAD

**Issue by wmszhe** [wmszhe/wmszhe.github.io#7]
https://blog.weandri.com/post/flutter-bian-yi-zhuo-mian-duan-app/ 

 温故而知新

**Comment by EryouHao** [comment]
好尝试！不知道开发体验与实现程度如何了？

**Comment by wmszhe** [comment]
> @EryouHao
> 好尝试！不知道开发体验与实现程度如何了？

我主要是做APP的，桌面端只是尝试，目前可以完全兼容APP端的代码，效果也不差。

但是 https://github.com/google/flutter-desktop-embedding 这个项目，明确写了

This is not an officially supported Google product.
The code and examples here, and the desktop Flutter libraries they use, are in early stages, and not intended for production use.

所以目前只是体验下
